/* Abareq recommendation layer: explainable rule-based matching, not generative AI. */
const i18n={
 ar:{navMenu:'القائمة',navStory:'الحكاية',navVisit:'الزيارة',directions:'الاتجاهات',eyebrow:'شاي على مهل · المدينة المنورة',heroTitle:'حين يصبح<br><em>الشاي مجلساً.</em>',heroCopy:'إبريق دافئ، ضوء كهرماني، ووقت لا يحتاج إلى استعجال.',viewMenu:'شاهد القائمة',callNow:'اتصل الآن <span>↗</span>',openNote:'الفرع الموثق في المبعوث · مفتوح حسب ساعات المحل المعتمدة',ratingLabel:'تقييم Google وقت البحث',reviewsLabel:'مراجعة عامة',districtLabel:'المبعوث · المدينة',verifyGoogle:'تحقق من Google Maps ↗',storyKicker:'روح المكان',storyTitle:'أباريق لا يقدم الشاي فقط.<br><em>يقدّم إيقاعاً.</em>',storyCopy:'من اسم المكان إلى الإبريق الذي يميّز حضوره، كل تفصيل هنا يدعو إلى التمهّل. شاي عراقي مبخر، دم الغزال، مكسرات، وحلويات تُقدّم في ضوء دافئ يشبه جلسة تعرفها من قبل.',storySubcopy:'الهوية مستوحاة من ألوان ورق القائمة، الخشب الداكن، النحاس الهادئ، والكنب الكريمي الظاهر في الصور العامة للمحل.',selectionKicker:'اختيارات أباريق',selectionTitle:'ابدأ من الإبريق.',selectionNote:'اختيارات مقترحة من الأسماء الظاهرة في قائمة المحل العامة.',teaDescription:'الاختيار الذي يبدأ منه اسم المكان.',cakeDescription:'حلوى ظاهرة في قائمة أباريق المصورة.',nutsDescription:'مرافقة بسيطة لإبريق أطول.',recommenderKicker:'المحرك الذكي',recommenderTitle:'دع مزاجك يختار.',recommenderNote:'أجب عن أسئلة قصيرة، وسنطابق ذوقك مع المنتجات المسجلة في قائمة أباريق.',questionMood:'ما الذي يناسب لحظتك؟',questionTaste:'أي طابع تفضّل؟',questionAmount:'كم تريد أن تشارك؟',moodCalm:'جلسة هادئة',moodEnergy:'أحتاج تركيزاً',moodSweet:'أرغب بحلوى',tasteStrong:'قوي ومركّز',tasteSpiced:'متبّل ودافئ',tasteFresh:'خفيف ومنعش',amountSolo:'لي وحدي',amountShare:'جلسة مشاركة',amountAny:'لا يهم',recommendationDisclaimer:'الترشيحات مبنية على سمات القائمة المنشورة، وليست ادعاءً بأن المنتج «الأفضل» مبيعاً.',browseAllProducts:'استعرض المنتجات كاملة',recommendationLoading:'نقرأ مزاجك…',recommendationTitle:'ترشيح أباريق لك',recommendationReason:'لماذا؟',recommendationMore:'شاهد التفاصيل والأسعار',menuKicker:'القائمة',menuTitle:'اختر مزاجك.',menuNote:'الأسعار الحالية مأخوذة من صور القائمة العامة وتحتاج اعتماد المحل قبل النشر النهائي.',all:'الكل',tea:'الشاي',coffee:'القهوة',desserts:'الحلويات',extras:'الإضافات',searchPlaceholder:'ابحث في القائمة',noResults:'لا توجد منتجات مطابقة لهذا البحث.',visitKicker:'الزيارة',visitTitle:'نراك في<br><em>المبعوث.</em>',visitCopy:'الفرع الموثق المتاح في المصادر العامة: شارع الأمير مقرن بن عبدالعزيز، حي المبعوث، المدينة المنورة.',openMap:'افتح الخريطة',phone:'+966 57 768 8820',footerNote:'شاي يُقدّم على مهل، في مدينة لا تُنسى.',sourceNote:'المعلومات العامة مرجعية وتتغير مع الوقت.'},
 en:{navMenu:'Menu',navStory:'The story',navVisit:'Visit',directions:'Directions',eyebrow:'Slow tea · Madinah',heroTitle:'When tea becomes<br><em>a gathering.</em>',heroCopy:'A warm pot, amber light, and time that does not need rushing.',viewMenu:'View menu',callNow:'Call now <span>↗</span>',openNote:'Verified Al Mabuth location · hours should be confirmed with the cafe',ratingLabel:'Google rating at research time',reviewsLabel:'public reviews',districtLabel:'Al Mabuth · Madinah',verifyGoogle:'Verify on Google Maps ↗',storyKicker:'The feeling',storyTitle:'Abareq serves more than tea.<br><em>It serves a rhythm.</em>',storyCopy:'From the name to the pot that carries its presence, every detail invites you to slow down. Iraqi steamed tea, Dam Al Ghazal, nuts, and desserts served in a warm light that feels familiar.',storySubcopy:'The identity draws from the menu paper, dark walnut, quiet copper, and cream seating visible in public images.',selectionKicker:'Abareq picks',selectionTitle:'Start with the pot.',selectionNote:'Suggested picks from the public menu names.',teaDescription:'The place to begin with Abareq.',cakeDescription:'A dessert shown in Abareq’s public menu.',nutsDescription:'A simple companion for a longer pot.',recommenderKicker:'Smart match',recommenderTitle:'Let your mood choose.',recommenderNote:'Answer a few questions and we will match your mood to the products in Abareq’s menu.',questionMood:'What fits your moment?',questionTaste:'Which profile do you prefer?',questionAmount:'How many are sharing?',moodCalm:'A calm session',moodEnergy:'I need focus',moodSweet:'I want dessert',tasteStrong:'Strong & focused',tasteSpiced:'Warm & spiced',tasteFresh:'Light & fresh',amountSolo:'Just me',amountShare:'A shared session',amountAny:'Either',recommendationDisclaimer:'Matches are based on menu attributes; they are not a claim about best-selling items.',browseAllProducts:'Browse the full menu',recommendationLoading:'Reading your mood…',recommendationTitle:'Your Abareq match',recommendationReason:'Why this?',recommendationMore:'See details & prices',menuKicker:'The menu',menuTitle:'Choose your mood.',menuNote:'Prices are transcribed from public menu photos and need cafe approval before final publication.',all:'All',tea:'Tea',coffee:'Coffee',desserts:'Desserts',extras:'Extras',searchPlaceholder:'Search the menu',noResults:'No products match this search.',visitKicker:'Visit',visitTitle:'See you in<br><em>Al Mabuth.</em>',visitCopy:'The publicly verified location: Prince Muqrin Ibn Abdulaziz Road, Al Mabuth, Madinah.',openMap:'Open map',phone:'+966 57 768 8820',footerNote:'Tea served slowly, in a city worth remembering.',sourceNote:'Public information is reference material and may change.'}
};
let lang='ar',products=[],answers={};
const qs=s=>document.querySelector(s),qsa=s=>[...document.querySelectorAll(s)];
const escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function applyLanguage(){const dict=i18n[lang];document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';qsa('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(dict[key]!=null)el.innerHTML=dict[key]});qsa('[data-i18n-placeholder]').forEach(el=>{el.placeholder=dict[el.dataset.i18nPlaceholder]});const toggle=qs('#langToggle');if(toggle)toggle.textContent=lang==='ar'?'EN':'ع';renderRecommendation()}
function scoreProduct(product){let score=0;const tags=product.tags||[];if(answers.mood==='calm'&&tags.includes('calm'))score+=4;if(answers.mood==='energy'&&(tags.includes('focused')||product.caffeine==='high'))score+=4;if(answers.mood==='sweet'&&tags.includes('sweet'))score+=5;if(answers.taste==='strong'&&tags.includes('strong'))score+=4;if(answers.taste==='spiced'&&tags.includes('spiced'))score+=4;if(answers.taste==='fresh'&&tags.includes('fresh'))score+=4;if(answers.amount==='solo'&&tags.includes('solo'))score+=2;if(answers.amount==='share'&&tags.includes('share'))score+=3;return score}
function renderRecommendation(){const result=qs('#recommendationResult');if(!result)return;if(Object.keys(answers).length<3){result.hidden=true;return}const dict=i18n[lang];const ranked=products.map(product=>({...product,score:scoreProduct(product)})).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name)).slice(0,5);result.hidden=false;result.innerHTML=`<div class="result-heading"><span class="result-spark">✦</span><div><span class="section-kicker">${dict.recommendationTitle}</span><h3>${lang==='ar'?'خمسة اختيارات قريبة من مزاجك':'Five matches for your mood'}</h3></div></div><div class="recommendation-list">${ranked.map((item,index)=>`<article class="recommendation-card"><span class="recommendation-rank">0${index+1}</span><div><h4>${escapeHtml(item.name)}</h4><p>${escapeHtml(item.reason)}</p></div><a href="products.html#product-${encodeURIComponent(item.name)}" class="text-link">${dict.recommendationMore} <span>↗</span></a></article>`).join('')}</div>`}
async function loadRecommendations(){try{const res=await fetch('data/recommendations.json',{cache:'no-store'});if(!res.ok)throw new Error('recommendations.json returned '+res.status);products=await res.json();renderRecommendation()}catch(error){console.error(error)}}
qsa('[data-answer]').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.answer;answers[key]=button.dataset.value;qsa(`[data-answer="${key}"]`).forEach(item=>item.classList.toggle('is-selected',item===button));renderRecommendation()}));
qs('#langToggle')?.addEventListener('click',()=>{lang=lang==='ar'?'en':'ar';applyLanguage()});applyLanguage();loadRecommendations();
const menuToggle=qs('#menuToggle'),siteNav=qs('#siteNav'),backToTop=qs('#backToTop'),scrollProgress=qs('#scrollProgress');
function closeMobileNav(){if(!menuToggle||!siteNav)return;menuToggle.setAttribute('aria-expanded','false');siteNav.classList.remove('is-open')}
menuToggle?.addEventListener('click',()=>{const open=menuToggle.getAttribute('aria-expanded')==='true';menuToggle.setAttribute('aria-expanded',String(!open));siteNav.classList.toggle('is-open',!open)});qsa('#siteNav a').forEach(link=>link.addEventListener('click',closeMobileNav));document.addEventListener('keydown',event=>{if(event.key==='Escape')closeMobileNav()});
const revealObserver='IntersectionObserver' in window?new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}}),{threshold:.12}):null;qsa('.story,.featured,.recommender-section,.visit,.site-footer').forEach(section=>{section.classList.add('reveal');revealObserver?.observe(section)});if(!revealObserver)qsa('.reveal').forEach(section=>section.classList.add('is-visible'));
function updateScrollUI(){const scrollable=document.documentElement.scrollHeight-window.innerHeight;const progress=scrollable>0?Math.min(100,(window.scrollY/scrollable)*100):0;if(scrollProgress)scrollProgress.style.width=`${progress}%`;backToTop?.classList.toggle('is-visible',window.scrollY>520)}window.addEventListener('scroll',updateScrollUI,{passive:true});updateScrollUI();backToTop?.addEventListener('click',()=>window.scrollTo({top:0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}));
