/* Abareq products page: data-driven cards and transparent prices. */
const i18n={ar:{home:'الرئيسية',story:'الحكاية',visit:'الزيارة',directions:'الاتجاهات',kicker:'قائمة أباريق',title:'اختر ما<br /><em>يشبه مزاجك.</em>',intro:'كل المنتجات الظاهرة في القائمة العامة، مرتبة لتقرأها بسرعة وتختار بهدوء.',all:'الكل',tea:'الشاي',coffee:'القهوة',desserts:'الحلويات',extras:'الإضافات',search:'ابحث في القائمة',note:'الأسعار من صور القائمة العامة، وتحتاج اعتماد المحل قبل النشر النهائي. عناوين الأحجام توضيحية عندما لا تظهر في الصورة بوضوح.',empty:'لا توجد منتجات مطابقة.',footer:'شاي يُقدّم على مهل، في مدينة لا تُنسى.',back:'العودة إلى الصفحة الرئيسية ↗',priceSingle:'سعر مفرد',confirm:'بحاجة اعتماد الأحجام'},en:{home:'Home',story:'The story',visit:'Visit',directions:'Directions',kicker:'Abareq menu',title:'Choose what<br /><em>fits your mood.</em>',intro:'Every product visible in the public menu, organised for a calm and quick choice.',all:'All',tea:'Tea',coffee:'Coffee',desserts:'Desserts',extras:'Extras',search:'Search the menu',note:'Prices are transcribed from public menu photos and need cafe approval. Size labels are indicative when the photo does not make them explicit.',empty:'No products match your search.',footer:'Tea served slowly, in a city worth remembering.',back:'Back to home ↗',priceSingle:'Single price',confirm:'Size labels need approval'}};
let lang='ar',items=[],category='all';const qs=s=>document.querySelector(s),qsa=s=>[...document.querySelectorAll(s)];
const escapeHtml=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function applyLanguage(){const dict=i18n[lang];document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';qsa('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(dict[key]!=null)el.innerHTML=dict[key]});qsa('[data-i18n-placeholder]').forEach(el=>el.placeholder=dict[el.dataset.i18nPlaceholder]);qs('#langToggle').textContent=lang==='ar'?'EN':'ع';render()}
function render(){const term=(qs('#productsSearch')?.value||'').trim().toLowerCase();const shown=items.filter(item=>(category==='all'||item.category===category)&&(!term||item.name.toLowerCase().includes(term)));const dict=i18n[lang];qs('#productsGrid').innerHTML=shown.map(item=>{const prices=item.prices||[];const labels=item.sizeLabels||[];const sizeMarkup=prices.length?prices.map((price,index)=>`<li><span>${escapeHtml(labels[index]||dict.priceSingle)}</span><strong>${escapeHtml(price)} <small>${lang==='ar'?'ر.س':'SAR'}</small></strong></li>`).join(''):`<li><span>${dict.priceSingle}</span><strong>${escapeHtml(item.price)} <small>${lang==='ar'?'ر.س':'SAR'}</small></strong></li>`;return `<article class="product-card" id="product-${encodeURIComponent(item.name)}"><div class="product-card-top"><span class="product-category">${escapeHtml(item.categoryLabel)}</span><span class="product-index">${String(shown.indexOf(item)+1).padStart(2,'0')}</span></div><h2>${escapeHtml(item.name)}</h2><p class="product-reason">${escapeHtml(item.reason)}</p><ul class="product-sizes">${sizeMarkup}</ul>${item.sizeLabelsNeedConfirmation?`<span class="approval-note">${dict.confirm}</span>`:''}</article>`}).join('');qs('#productsEmpty').hidden=shown.length>0}
qsa('.product-tab').forEach(btn=>btn.addEventListener('click',()=>{qsa('.product-tab').forEach(tab=>{tab.classList.remove('active');tab.setAttribute('aria-selected','false')});btn.classList.add('active');btn.setAttribute('aria-selected','true');category=btn.dataset.category;render()}));qsa('.product-tab').forEach(btn=>btn.setAttribute('role','tab'));qs('#productsSearch').addEventListener('input',render);qs('#langToggle').addEventListener('click',()=>{lang=lang==='ar'?'en':'ar';applyLanguage()});
async function load(){try{const res=await fetch('data/recommendations.json',{cache:'no-store'});if(!res.ok)throw new Error('recommendations.json returned '+res.status);items=await res.json();render()}catch(error){console.error(error);qs('#productsGrid').innerHTML='<p class="empty-state">تعذر تحميل القائمة حالياً.</p>'}}
applyLanguage();load();
